### ISSUE TITLE
Make stars yellow on hover/click.

### ISSUE THREAD

**Issue by carcols** [fabd/kanji-koohii#49]
Previously, when one wanted to "star" a story, when hovering the star would become yellow. On the new version the star stays always gray... which is fine but I guess everyone is conditioned to expect it to become yellow. It would be useful if the star would stay yellow once one "stars" a story, as it used to be.

**Comment by carcols** [comment]
PS: I think the same could apply to the "report" button, that now is always red by default.

**Comment by fabd** [comment]
I think you mean that it should be gray by default and turn red only on :hover. I agree.

**Comment by carcols** [comment]
I see that currently the "hover" part is solved, however the icons do not stay colored (red or yellow) once I star or report a story: for the starred stories they are at least on the "favorite" section, but for the reported stories now there's no way to know if I already reported the story or not.

![image](https://cloud.githubusercontent.com/assets/11387647/22863081/6e4072e8-f13a-11e6-87cc-4422c0b11360.png)

**Comment by carcols** [comment]
For clarification: I think the star on the top story I starred should be yellow, the same as all stories I report below.

**Comment by fabd** [comment]
@carcols I agree and I can think of one way to do it that works with the caching of the pages. Which is why the issue remains open. Thanks for the great feedback :+1:
